language: node_js
node_js:
  - "stable"
env:
  global:
  - export NODE_ENV=test
before_script:
  - npm install
script:
  - npm test
after_success: 
  - npm run coverage
  - npm run report-coverage
  - npm run coveralls